### ISSUE TITLE
File/Folder details in SharedSpace 

### ISSUE THREAD

**Issue by hoangdat** [linagora/linshare-mobile-flutter-app#364]
### Story: 
#283: UC1 - 2

### DoD:

**Comment by datnguyenhuy** [comment]
By design, last name should be uppercase
The description field cannot be edited or added 
![image.png](https://images.zenhubusercontent.com/606bcc9093306911d9ef4d58/a788271d-af4d-444c-8278-6e24c62707a0)
![image.png](https://images.zenhubusercontent.com/606bcc9093306911d9ef4d58/cd1320ad-85ab-4eab-9217-4c0fd05c0156)

**Comment by hantt12** [comment]
Minor issue: https://github.com/linagora/linshare-mobile-flutter-app/issues/447
