### ISSUE TITLE
Unable to scroll in workgroup detail screen

### ISSUE THREAD

**Issue by hantt12** [linagora/linshare-mobile-flutter-app#464]
#### Reproduction Steps
1. View app in landscape
2. Go to Shared Space
3. View details of a certain workgroup

### Expected result
Should be able to see all the details

### Current behavior
Unable to scroll to view all details (no description details)

### Context
Iphone 11
Linshare app 0.8.0

### Additional information

frequency, log files,...

**Comment by huynguyennovem** [comment]
Confirm this bug is fixed in ver 2.0.0
https://github.com/linagora/linshare-mobile-flutter-app/commit/d291b74c233dbf7b35a4c16efe2f2ebefa1cfcc8

![Simulator Screen Shot - iPhone 12 Pro HuyNQ - 2021-10-01 at 17.51.35.png](https://images.zenhubusercontent.com/605175c4593ffb54122f0753/0155d952-587f-4d72-b574-4bc19320a942)
